services:
 postgres:
  container_name: postgres_container
  image: postgres:10
  environment:
  - 'POSTGRES_USER=postgres'
  - 'POSTGRES_PASSWORD=postgres'
  ports:
  - 5433:5433
  volumes:
  - data:/var/lib/postgresql/data
 pgadmin:
  container_name: pgadmin
  image: dpage/pgadmin4
  ports:
  - 8888:8888
  environment:
  - 'PGADMIN_DEFAULT_EMAIL=admin@example.com'
  - 'PGADMIN_DEFAULT_PASSWORD=admin'
  - 'PGADMIN_LISTEN_PORT=8888'

volumes:
  data: